apiVersion: v2
name: kube-prometheus-stack
description: Kube Prometheus Stack in agent mode for remote metrics
version: 1.0.0
type: application
dependencies:
  - name: kube-prometheus-stack
    version: 82.0.1
    repository: https://prometheus-community.github.io/helm-charts
