apiVersion: v2
name: prometheus-operator-crds
description: Prometheus Operator CRDs
version: 1.0.0
type: application
dependencies:
  - name: prometheus-operator-crds
    version: 27.0.0
    repository: https://prometheus-community.github.io/helm-charts
